### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by SirNoName2705** [yooksi/pz-zdoc#4]
Hey yooksi,
i do not understand your installation tutorial. May you help me with that issue :).

**Comment by SirNoName2705** [comment]
![error](https://user-images.githubusercontent.com/66351995/102355815-ab8cfa80-3fac-11eb-8e0c-10b9f9d83723.PNG)
here is my error, but i do think the problem here is my incompetency rather than ur code ^^

**Comment by matshou** [comment]
Thank you for showing interest in using the project!

You have to specify a direct API page link. For example, to get a list of all exposed methods (and referenced members) you would want to parse and compile `LuaManager.GlobalObject.html`. Structure you command like this:

```
java -a https://projectzomboid.com/modding/zombie/Lua/LuaManager.GlobalObject.html -o ./pzdoc
```

I am currently working on a new release that will read the exposed classes directly from Project Zomboid classes (in game install directory) and then compile them with appropriate documentation from API JavaDoc (if available) rather then making the user manually direct the application to compile each individual file. Since the current API documentation is out of date and many exposed classes are not documented this approach will have an advantage of resulting in up-to-date Lua library output. 

I am almost done so hopefully this release will hit the master branch in few days if I don't get too distracted with life stuff. Make sure to watch the repository, in the meantime I hope you find the current version useful enough to help your modding efforts.

**Comment by SirNoName2705** [comment]
BTW your explanation helped. I wrote an email to your email which is displayed on your github Profil. I look forward to hear from you.
